components up message

diff --git a/.github/workflows/phantomjs-test.yml b/.github/workflows/phantomjs-test.yml
--- a/.github/workflows/phantomjs-test.yml
+++ b/.github/workflows/phantomjs-test.yml
@@ -73,7 +73,8 @@ jobs:
           docker-compose logs api
           echo "Component 'web' Logs:"
           docker-compose logs web
-          confailed=`echo "$constat" | grep -i "exit"`; if [ -n "$confailed" ]; then echo "Components failed!" && echo "$confailed" && exit 1 ; fi ;
+          confailed=`echo "$constat" | grep -i "exit"` 
+          if [ -n "$confailed" ]; then echo "Components failed:" && echo "$confailed" && exit 1 ; else echo "Components UP" ; fi ;
 
       - name: Starting Test Sequences
         run: echo "Starting Test Sequences"
