separate components up message

diff --git a/.github/workflows/phantomjs-test.yml b/.github/workflows/phantomjs-test.yml
--- a/.github/workflows/phantomjs-test.yml
+++ b/.github/workflows/phantomjs-test.yml
@@ -73,8 +73,10 @@ jobs:
           docker-compose logs api
           echo "Component 'web' Logs:"
           docker-compose logs web
-          confailed=`echo "$constat" | grep -i "exit"` 
-          if [ -n "$confailed" ]; then echo "Components failed:" && echo "$confailed" && exit 1 ; else echo "Components UP" ; fi ;
+          confailed=`echo "$constat" | grep -i "exit"`
+          echo "comp failed:" $confailed 
+          if [ -z "$confailed" ]; then echo "Components UP" ; fi ;
+          if [ -n "$confailed" ]; then echo "Components failed:" && echo "$confailed" && exit 1 ; fi ;
 
       - name: Starting Test Sequences
         run: echo "Starting Test Sequences"
